name: Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and run container.
    - run: |
        sudo docker stop Suwie
        sudo docker rm Suwie
        sudo docker build portfolio ./CICD/frontend
        sudo docker run -d -p 3000:3000 --name Suwie portfolio
        
