name: Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pull projeckt    
      run: cd /home/ubuntu/CICD/ && git pull
    - run: |
        sudo docker stop Suwie
        sudo docker rm Suwie
        sudo docker build -t portfolio /home/ubuntu/CICD/frontend
        sudo docker run -d -p 3000:3000 --name Suwie portfolio        
