name: Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and run container.
    - run: sudo docker stop Suwie
    - run: sudo docker rm Suwie
    - run: sudo docker build portfolio ./CICD/frontend
    - run: sudo docker run -d -p 3000:3000 --name Suwie portfolio
        
