name: Docker run/Node test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  node-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v2
      with:
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    - name: Pull projeckt    
      run: cd /home/ubuntu/CICD/ && git pull
    - run: npm ci --prefix frontend/
    - run: npm run build --if-present --prefix frontend/

  docker-run:
    
    runs-on: self-hosted
    needs: node-test

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        sudo docker stop Suwie
        sudo docker rm Suwie
        sudo docker build -t portfolio /home/ubuntu/CICD/frontend
        sudo docker run -d -p ${{secrets.DOCKER_PORT}}:${{secrets.DOCKER_PORT}} --name Suwie portfolio        
